Repository apify/apify-sdk-js, pull requests merged in 2023-10, with the labels that each got.

#231 docs: enable `Run on Apify` buttons on all examples
  .github/workflows/docs.yaml
  .github/workflows/release.yaml
  .github/workflows/test-and-release.yaml
  docs/examples/add_data_to_dataset.mdx
  docs/examples/basic_crawler.mdx
  docs/examples/cheerio_crawler.mdx
  docs/examples/crawl_all_links.mdx
  docs/examples/crawl_multiple_urls.mdx
  docs/examples/crawl_relative_links.mdx
  docs/examples/crawl_single_url.mdx
  docs/examples/crawl_sitemap.mdx
  docs/examples/crawl_sitemap_playwright.ts
  docs/examples/crawl_some_links.mdx
  docs/examples/forms.mdx
  docs/examples/map_and_reduce.mdx
  docs/examples/playwright_crawler.mdx
  docs/examples/puppeteer_capture_screenshot.mdx
  docs/examples/puppeteer_crawler.mdx
  docs/examples/puppeteer_recursive_crawl.mdx
  docs/examples/puppeteer_with_proxy.mdx
  website/package-lock.json
  website/package.json
  website/versioned_docs/version-3.1/examples/add_data_to_dataset.mdx
  website/versioned_docs/version-3.1/examples/basic_crawler.mdx
  website/versioned_docs/version-3.1/examples/cheerio_crawler.mdx
  website/versioned_docs/version-3.1/examples/crawl_all_links.mdx
  website/versioned_docs/version-3.1/examples/crawl_multiple_urls.mdx
  website/versioned_docs/version-3.1/examples/crawl_relative_links.mdx
  website/versioned_docs/version-3.1/examples/crawl_single_url.mdx
  website/versioned_docs/version-3.1/examples/crawl_sitemap.mdx
  website/versioned_docs/version-3.1/examples/crawl_sitemap_playwright.ts
  website/versioned_docs/version-3.1/examples/crawl_some_links.mdx
  website/versioned_docs/version-3.1/examples/forms.mdx
  website/versioned_docs/version-3.1/examples/map_and_reduce.mdx
  website/versioned_docs/version-3.1/examples/playwright_crawler.mdx
  website/versioned_docs/version-3.1/examples/puppeteer_capture_screenshot.mdx
  website/versioned_docs/version-3.1/examples/puppeteer_crawler.mdx
  website/versioned_docs/version-3.1/examples/puppeteer_recursive_crawl.mdx
  website/versioned_docs/version-3.1/examples/puppeteer_with_proxy.mdx
Labels: product roadmap, t-tooling

#235 fix: run the whole `Actor.exit()` code inside a timeout handler
  package-lock.json
  packages/apify/package.json
  packages/apify/src/actor.ts
  renovate.json
Labels: adhoc, t-tooling

#236 fix: add more logging to `Actor.init` and `Actor.exit`
  packages/apify/src/actor.ts
Labels: adhoc, t-tooling

#240 chore: wow e2e e2e's again
  .eslintrc.json
  .github/workflows/test-e2e.yaml
  package-lock.json
  package.json
  test/e2e/.eslintrc.json
  test/e2e/cheerio-default/test.mjs
  test/e2e/cheerio-ignoreSslErrors-disabled/test.mjs
  test/e2e/cheerio-ignoreSslErrors-enabled/test.mjs
  test/e2e/cheerio-initial-cookies/test.mjs
  test/e2e/cheerio-max-requests/test.mjs
  test/e2e/cheerio-page-info/test.mjs
  test/e2e/jsdom-default/test.mjs
  test/e2e/jsdom-initial-cookies/test.mjs
  test/e2e/jsdom-max-requests/test.mjs
  test/e2e/jsdom-page-info/test.mjs
  test/e2e/playwright-default/test.mjs
  test/e2e/playwright-initial-cookies/test.mjs
  test/e2e/puppeteer-default/test.mjs
  test/e2e/puppeteer-ignoreSslErrors-disabled/test.mjs
  test/e2e/puppeteer-ignoreSslErrors-enabled/test.mjs
  test/e2e/puppeteer-initial-cookies/test.mjs
  test/e2e/puppeteer-page-info/test.mjs
  test/e2e/puppeteer-store-pagination-jquery/test.mjs
  test/e2e/puppeteer-store-pagination/test.mjs
  test/e2e/web-default/test.mjs
  test/e2e/web-dev-mode/test.mjs
  test/e2e/web-ignoreSslErrors-disabled/test.mjs
  test/e2e/web-ignoreSslErrors-enabled/test.mjs
  test/e2e/web-initial-cookies/test.mjs
  test/e2e/web-page-info/test.mjs
  test/e2e/web-proxy-rotation-works/test.mjs
  test/e2e/web-store-pagination/test.mjs
  tsconfig.eslint.json
Labels: adhoc, t-tooling, tested

#243 docs: add "Edit this Page" link to the docs
  website/docusaurus.config.js
Labels: adhoc, t-tooling

#247 chore: migrate e2e tests to new site
  test/e2e/cheerio-ignoreSslErrors-disabled/test.mjs
  test/e2e/cheerio-page-info/test.mjs
  test/e2e/jsdom-page-info/test.mjs
  test/e2e/puppeteer-page-info/test.mjs
  test/e2e/puppeteer-store-pagination-jquery/test.mjs
  test/e2e/puppeteer-store-pagination/test.mjs
  test/e2e/tools.mjs
  test/e2e/web-page-info/test.mjs
  test/e2e/web-store-pagination/test.mjs
Labels: adhoc, t-tooling, tested
