Repository apify/apify-sdk-js, pull requests merged in 2023-11, with the labels that each got.

#250 docs: update favicon and improve deployment workflow
  .github/workflows/docs.yaml
  website/docusaurus.config.js
Labels: adhoc, debt, t-tooling

#251 docs: fix all broken links and enforce we dont add new ones
  website/docusaurus.config.js
  website/src/components/ApiLink.jsx
  website/src/theme/NavbarItem/DocsVersionDropdownNavbarItem.js
  website/versioned_docs/version-1.3/examples/basic_crawler.md
  website/versioned_docs/version-1.3/examples/call_actor.md
  website/versioned_docs/version-1.3/examples/cheerio_crawler.md
  website/versioned_docs/version-1.3/examples/crawl_relative_links.md
  website/versioned_docs/version-1.3/examples/crawl_single_url.md
  website/versioned_docs/version-1.3/examples/crawl_some_links.md
  website/versioned_docs/version-1.3/examples/forms.md
  website/versioned_docs/version-1.3/examples/map_and_reduce.md
  website/versioned_docs/version-1.3/examples/puppeteer_crawler.md
  website/versioned_docs/version-1.3/examples/puppeteer_recursive_crawl.md
  website/versioned_docs/version-1.3/examples/puppeteer_sitemap.md
  website/versioned_docs/version-1.3/examples/screenshots.md
  website/versioned_docs/version-1.3/guides/quick_start.md
  website/versioned_docs/version-1.3/guides/request_storage.md
  website/versioned_docs/version-1.3/typedefs/DatasetConsumer.md
  website/versioned_docs/version-1.3/typedefs/DatasetMapper.md
  website/versioned_docs/version-1.3/typedefs/DatasetReducer.md
  website/versioned_docs/version-1.3/typedefs/KeyConsumer.md
  website/versioned_docs/version-1.3/typedefs/RequestTransform.md
  website/versioned_docs/version-2.3/examples/basic_crawler.md
  website/versioned_docs/version-2.3/examples/call_actor.md
  website/versioned_docs/version-2.3/examples/cheerio_crawler.md
  website/versioned_docs/version-2.3/examples/crawl_relative_links.md
  website/versioned_docs/version-2.3/examples/crawl_single_url.md
  website/versioned_docs/version-2.3/examples/crawl_some_links.md
  website/versioned_docs/version-2.3/examples/forms.md
  website/versioned_docs/version-2.3/examples/map_and_reduce.md
  website/versioned_docs/version-2.3/examples/puppeteer_crawler.md
  website/versioned_docs/version-2.3/examples/puppeteer_recursive_crawl.md
  website/versioned_docs/version-2.3/guides/request_storage.md
  website/versioned_docs/version-2.3/guides/result_storage.md
  website/versioned_docs/version-2.3/typedefs/DatasetConsumer.md
  website/versioned_docs/version-2.3/typedefs/DatasetMapper.md
  website/versioned_docs/version-2.3/typedefs/DatasetReducer.md
  website/versioned_docs/version-2.3/typedefs/KeyConsumer.md
  website/versioned_docs/version-2.3/typedefs/RequestTransform.md
  website/versioned_docs/version-3.1/guides/result_storage.mdx
Labels: t-tooling

#252 fix(apify): declare got-scraping as dependency
  package-lock.json
  packages/apify/package.json
Labels: adhoc, t-tooling

#255 docs: add monetization webinar banner
  packages/actor-scraper/cheerio-scraper/README.md
  packages/actor-scraper/jsdom-scraper/README.md
  packages/actor-scraper/playwright-scraper/README.md
  packages/actor-scraper/puppeteer-scraper/README.md
  packages/actor-scraper/web-scraper/README.md
Labels: documentation, adhoc, t-tooling

#256 docs: remove the monetization banner and h1 from actors
  packages/actor-scraper/cheerio-scraper/README.md
  packages/actor-scraper/jsdom-scraper/README.md
  packages/actor-scraper/playwright-scraper/README.md
  packages/actor-scraper/puppeteer-scraper/README.md
  packages/actor-scraper/web-scraper/README.md
Labels: documentation, adhoc, t-tooling

#233 chore: support got-scraping v4
  jest.config.js
  package-lock.json
  package.json
  packages/actor-scraper/cheerio-scraper/src/internals/crawler_setup.ts
  packages/actor-scraper/cheerio-scraper/src/main.ts
  packages/actor-scraper/jsdom-scraper/src/internals/crawler_setup.ts
  packages/actor-scraper/jsdom-scraper/src/main.ts
  packages/actor-scraper/playwright-scraper/src/internals/crawler_setup.ts
  packages/actor-scraper/playwright-scraper/src/main.ts
  packages/actor-scraper/puppeteer-scraper/src/internals/crawler_setup.ts
  packages/actor-scraper/puppeteer-scraper/src/main.ts
  packages/actor-scraper/web-scraper/src/internals/bundle.browser.ts
  packages/actor-scraper/web-scraper/src/internals/crawler_setup.ts
  packages/actor-scraper/web-scraper/src/main.ts
  packages/apify/package.json
  packages/apify/src/actor.ts
  packages/apify/src/platform_event_manager.ts
  packages/apify/src/proxy_configuration.ts
  packages/apify/src/utils.ts
  packages/apify/tsconfig.build.json
  packages/scraper-tools/src/browser_tools.ts
  packages/scraper-tools/src/context.ts
  packages/scraper-tools/src/run_actor.ts
  packages/scraper-tools/src/tools.ts
  test/MemoryStorageEmulator.ts
  test/apify/actor.test.ts
  test/apify/events.test.ts
  test/apify/proxy_configuration.test.ts
  test/apify/utils.test.ts
  test/scraper-tools/browser_tools.test.ts
  test/scraper-tools/tools.test.ts
  test/tsconfig.json
  tsconfig.eslint.json
  vitest.config.ts
Labels: adhoc, t-tooling, tested

#261 chore(e2e): increase timeout to leave more space for tests to finish
  test/e2e/puppeteer-store-pagination-jquery/test.mjs
  test/e2e/puppeteer-store-pagination/test.mjs
  test/e2e/tools.mjs
  test/e2e/web-dev-mode/test.mjs
Labels: adhoc, t-tooling, tested
