Repository apify/apify-sdk-js, pull requests merged in 2024-08, with the labels that each got.

#316 chore: update dependency on `ws`
  package-lock.json
  package.json
  packages/apify/package.json
  packages/apify/src/key_value_store.ts
  packages/apify/src/platform_event_manager.ts
  test/apify/events.test.ts
Labels: adhoc, t-tooling, tested

#317 chore: update dev dependencies
  package-lock.json
  package.json
  packages/scraper-tools/package.json
  packages/scraper-tools/src/browser_tools.ts
  turbo.json
Labels: adhoc, t-tooling

#320 feat: add `metaOrigin` to `Actor.config`
  packages/apify/src/configuration.ts
Labels: adhoc, t-platform
