Repository apify/apify-sdk-js, pull requests merged in 2024-10, with the labels that each got.

#326 fix: decode special characters in proxy `username` and `password`
  package-lock.json
  package.json
  packages/apify/src/proxy_configuration.ts
  test/apify/proxy_configuration.test.ts
Labels: adhoc, t-tooling, tested

#328 feat: add standby URL, change default port
  packages/apify/src/configuration.ts
Labels: t-platform

#330 docs: bump `@apify/docusaurus-plugin-typedoc-api`
  website/package-lock.json
  website/package.json
Labels: adhoc, t-tooling

#332 chore: update generic scrapers
  package-lock.json
  packages/actor-scraper/cheerio-scraper/CHANGELOG.md
  packages/actor-scraper/jsdom-scraper/CHANGELOG.md
  packages/actor-scraper/playwright-scraper/CHANGELOG.md
  packages/actor-scraper/puppeteer-scraper/CHANGELOG.md
  packages/actor-scraper/web-scraper/CHANGELOG.md
Labels: adhoc, t-tooling

#334 fix: remove zwsp characters from markdown docs
  docs/guides/docker_images.mdx
  docs/guides/proxy_management.mdx
  docs/guides/session_management.mdx
  website/versioned_docs/version-3.0/guides/docker_images.mdx
  website/versioned_docs/version-3.0/guides/proxy_management.mdx
  website/versioned_docs/version-3.0/guides/session_management.mdx
  website/versioned_docs/version-3.1/guides/docker_images.mdx
  website/versioned_docs/version-3.1/guides/proxy_management.mdx
  website/versioned_docs/version-3.1/guides/session_management.mdx
  website/versioned_docs/version-3.2/guides/docker_images.mdx
  website/versioned_docs/version-3.2/guides/proxy_management.mdx
  website/versioned_docs/version-3.2/guides/session_management.mdx
Labels: t-tooling
