Repository apify/apify-sdk-js, pull requests merged in 2024-04, with the labels that each got.

#292 fix: Smartlook for docs build token [internal]
  .github/workflows/docs.yaml
Labels: adhoc, t-web

#293 docs(actor-scraper): use RequestQueueV2 for all Actor scrapers
  packages/actor-scraper/cheerio-scraper/CHANGELOG.md
  packages/actor-scraper/jsdom-scraper/CHANGELOG.md
  packages/actor-scraper/playwright-scraper/CHANGELOG.md
  packages/actor-scraper/puppeteer-scraper/CHANGELOG.md
  packages/actor-scraper/web-scraper/CHANGELOG.md
Labels: adhoc, t-platform

#290 feat: support for proxy tiers
  package-lock.json
  package.json
  packages/apify/package.json
  packages/apify/src/proxy_configuration.ts
  test/apify/proxy_configuration.test.ts
Labels: adhoc, t-tooling, tested

#294 chore: Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: adhoc, t-tooling
