Repository apify/apify-sdk-js, pull requests merged in 2025-04, with the labels that each got.

#373 chore: Update Crawlee and fix related issues
  packages/actor-scraper/puppeteer-scraper/src/internals/crawler_setup.ts
  packages/actor-scraper/web-scraper/src/internals/crawler_setup.ts
  packages/apify/src/proxy_configuration.ts
  test/apify/events.test.ts
Labels: adhoc, t-tooling, tested

#358 feat: sign record's public url
  package-lock.json
  package.json
  packages/apify/package.json
  packages/apify/src/configuration.ts
  packages/apify/src/key_value_store.ts
  test/e2e/sdk/publicUrl/src/main.mjs
  test/e2e/sdk/publicUrl/test.mjs
Labels: t-platform, tested

#376 chore: update lockfile
  .github/workflows/docs.yaml
  .github/workflows/release.yaml
  .github/workflows/test-and-release.yaml
  .github/workflows/test-e2e.yaml
  eslint.config.mjs
  package-lock.json
  package.json
  packages/actor-scraper/camoufox-scraper/src/internals/consts.ts
  packages/apify/src/utils.ts
  test/apify/actor.test.ts
  test/apify/events.test.ts
  test/apify/proxy_configuration.test.ts
  test/apify/utils.test.ts
  test/tsconfig.json
  website/package-lock.json
Labels: adhoc, t-tooling, tested

#380 chore(ci): add automatic release workflow for generic Actors
  .github/workflows/release-generic-actors.yaml
  packages/actor-scraper/cheerio-scraper/.actor/actor.json
  packages/actor-scraper/jsdom-scraper/.actor/actor.json
  packages/actor-scraper/playwright-scraper/.actor/actor.json
  packages/actor-scraper/puppeteer-scraper/.actor/actor.json
  packages/actor-scraper/web-scraper/.actor/actor.json
  packages/actor-scraper/web-scraper/apify.json
Labels: adhoc, t-tooling

#381 chore(ci): fix automatic Actor build versioning
  .github/workflows/release-generic-actors.yaml
  package-lock.json
  packages/actor-scraper/camoufox-scraper/Dockerfile
  packages/actor-scraper/camoufox-scraper/package.json
Labels: adhoc, t-tooling

#382 chore: align generic scraper defaults with new `crawlee.dev` structure
  packages/actor-scraper/camoufox-scraper/INPUT_SCHEMA.json
  packages/actor-scraper/cheerio-scraper/INPUT_SCHEMA.json
  packages/actor-scraper/jsdom-scraper/INPUT_SCHEMA.json
  packages/actor-scraper/playwright-scraper/INPUT_SCHEMA.json
  packages/actor-scraper/puppeteer-scraper/INPUT_SCHEMA.json
  packages/actor-scraper/web-scraper/INPUT_SCHEMA.json
Labels: adhoc, t-tooling

#383 fix: convert `@apilink` to `@link` on build
  package-lock.json
  package.json
  packages/apify/package.json
  scripts/temp_fix_apify_exports.mjs
  scripts/temp_fix_apify_exports.ts
  tools/build_readme.js
  tools/typescript_fixes.js
  tools/typescript_interfaces.js
Labels: adhoc, t-tooling
