Repository apify/apify-sdk-js, pull requests merged in 2025-02, with the labels that each got.

#354 ci: Fix import in e2e tests
  test/e2e/scrapers/cheerio-default/test.mjs
  test/e2e/scrapers/cheerio-ignoreSslErrors-disabled/test.mjs
  test/e2e/scrapers/cheerio-ignoreSslErrors-enabled/test.mjs
  test/e2e/scrapers/cheerio-initial-cookies/test.mjs
  test/e2e/scrapers/cheerio-max-requests/test.mjs
  test/e2e/scrapers/cheerio-page-info/test.mjs
  test/e2e/scrapers/jsdom-default/test.mjs
  test/e2e/scrapers/jsdom-initial-cookies/test.mjs
  test/e2e/scrapers/jsdom-max-requests/test.mjs
  test/e2e/scrapers/jsdom-page-info/test.mjs
  test/e2e/scrapers/playwright-default/test.mjs
  test/e2e/scrapers/playwright-initial-cookies/test.mjs
  test/e2e/scrapers/puppeteer-default/test.mjs
  test/e2e/scrapers/puppeteer-ignoreSslErrors-disabled/test.mjs
  test/e2e/scrapers/puppeteer-ignoreSslErrors-enabled/test.mjs
  test/e2e/scrapers/puppeteer-initial-cookies/test.mjs
  test/e2e/scrapers/puppeteer-page-info/test.mjs
  test/e2e/scrapers/puppeteer-store-pagination-jquery/test.mjs
  test/e2e/scrapers/puppeteer-store-pagination/test.mjs
  test/e2e/scrapers/web-default/test.mjs
  test/e2e/scrapers/web-dev-mode/test.mjs
  test/e2e/scrapers/web-ignoreSslErrors-disabled/test.mjs
  test/e2e/scrapers/web-ignoreSslErrors-enabled/test.mjs
  test/e2e/scrapers/web-initial-cookies/test.mjs
  test/e2e/scrapers/web-page-info/test.mjs
  test/e2e/scrapers/web-proxy-rotation-works/test.mjs
  test/e2e/scrapers/web-store-pagination/test.mjs
Labels: adhoc, t-tooling, tested

#356 docs: Actor.charge guide
  docs/guides/code/actor_charge.ts
  docs/guides/code/conditional_actor_charge.ts
  docs/guides/pay_per_event.mdx
  packages/apify/src/actor.ts
  packages/apify/src/charging.ts
  packages/apify/src/index.ts
  website/sidebars.js
Labels: t-tooling

#360 fix: Add workaround for incorrect handling of maxTotalChargeUsd
  packages/apify/src/charging.ts
Labels: adhoc, t-tooling

#361 fix: ensure `maxTotalChargeUsd` is correctly mapped to number, consider empty string as infinity
  package-lock.json
  packages/apify/package.json
  packages/apify/src/charging.ts
  packages/apify/src/configuration.ts
  test/apify/actor.test.ts
Labels: adhoc, t-tooling, tested

#364 feat: add Camoufox-based generic Actor
  package-lock.json
  packages/actor-scraper/camoufox-scraper/.actor/actor.json
  packages/actor-scraper/camoufox-scraper/.dockerignore
  packages/actor-scraper/camoufox-scraper/Dockerfile
  packages/actor-scraper/camoufox-scraper/INPUT_SCHEMA.json
  packages/actor-scraper/camoufox-scraper/README.md
  packages/actor-scraper/camoufox-scraper/package.json
  packages/actor-scraper/camoufox-scraper/src/internals/consts.ts
  packages/actor-scraper/camoufox-scraper/src/internals/crawler_setup.ts
  packages/actor-scraper/camoufox-scraper/src/main.ts
  packages/actor-scraper/camoufox-scraper/tsconfig.json
Labels: adhoc, t-tooling
