Repository apify/apify-sdk-js, pull requests merged in 2025-05, with the labels that each got.

#385 fix: prefer proxy password from env var
  packages/apify/src/proxy_configuration.ts
  test/apify/proxy_configuration.test.ts
Labels: t-platform, tested

#386 fix: improve check for crawlee version mismatch
  packages/apify/src/utils.ts
Labels: adhoc, t-tooling

#394 fix: improve extension of `Configuration` class to fix issues in native ESM projects
  packages/apify/src/configuration.ts
Labels: adhoc, t-tooling

#393 fix(scrapers): Use RequestQueue directly to avoid excessive RQ writes on runs with large startUrls list
  package-lock.json
  package.json
  packages/actor-scraper/camoufox-scraper/src/internals/crawler_setup.ts
  packages/actor-scraper/cheerio-scraper/package.json
  packages/actor-scraper/cheerio-scraper/src/internals/crawler_setup.ts
  packages/actor-scraper/jsdom-scraper/src/internals/crawler_setup.ts
  packages/actor-scraper/playwright-scraper/src/internals/crawler_setup.ts
  packages/actor-scraper/puppeteer-scraper/src/internals/crawler_setup.ts
  packages/actor-scraper/web-scraper/src/internals/crawler_setup.ts
Labels: t-tooling

#396 docs: Improve ChargeResult and ChargeOptions documentation
  packages/apify/src/actor.ts
  packages/apify/src/charging.ts
Labels: t-tooling
